### ISSUE TITLE
关于物体匹配

### ISSUE THREAD

**Issue by fuzhao123232** [zhangxy0517/3D-Registration-with-Maximal-Cliques#11]
请问作者这个适合物体匹配吗，目前在我自己的数据集上测试效果不佳
![image](https://github.com/zhangxy0517/3D-Registration-with-Maximal-Cliques/assets/115547529/8049b36f-974f-4135-9629-b31218ab8ee3)

**Comment by zhangxy0517** [comment]
适用。MAC的输入是匹配，因此对不同类型的点云是通用的，论文中我们也测试了模型数据库U3M。配准失败的原因可能是特征描述产生匹配的质量很低，也可能是参数设置不合理。

**Comment by fuzhao123232** [comment]
感谢作者的指教，已解决。作者的python代码中对final_trans的选择是计算了一个MAE分数，但是对我不适用，我将之替换为fitness（就是两点云的重叠面积），然后选择fitness最大的作为final_trans后，取得非常好的效果。只是很奇怪为什么会有这样的结果，还是说fitness比MAE更鲁棒？
![image](https://github.com/zhangxy0517/3D-Registration-with-Maximal-Cliques/assets/115547529/b784dad0-8f8c-4839-97d8-ea8914618f3a)

**Comment by Guangyun-Xu** [comment]
> 感谢作者的指教，已解决。作者的python代码中对final_trans的选择是计算了一个MAE分数，但是对我不适用，我将之替换为fitness（就是两点云的重叠面积），然后选择fitness最大的作为final_trans后，取得非常好的效果。只是很奇怪为什么会有这样的结果，还是说fitness比MAE更鲁棒？ ![image](https://user-images.githubusercontent.com/115547529/251058095-b784dad0-8f8c-4839-97d8-ea8914618f3a.png)

大佬，你的fitness是怎么算的，可否给个代码参考一下

**Comment by fuzhao123232** [comment]
我是把所有的pose都跑了open3d的icp配准,然后只迭代一次,不然会很慢,这样就很快,几乎没花什么时间,然后配准的结果里面有fitness和rmse两个指标
