### ISSUE TITLE
Python test usage on custom point clouds

### ISSUE THREAD

**Issue by ttsesm** [zhangxy0517/3D-Registration-with-Maximal-Cliques#2]
Hi @zhangxy0517,

Can you elaborate a bit how I can use the MAC on custom point clouds using the python implementation. Let's say I have pcd1.ply and pcd2.ply. If I understand correctly I need to first run the MAC binary that I have compiled to create the correspondence files and then feed these into the `main.py` script? Is that correct?

I think it would be nice if you could provide a step by step example given two pcds.

Thanks.

**Comment by zhangxy0517** [comment]
@ttsesm MAC estimates transformation from given correspondences, so the input should be correspondences generated by the feature descriptor. I have uploaded a step-by-step example `exmaple_with_fpfh.py`

**Comment by ttsesm** [comment]
Thanks a lot.
Looks good ;-)
