### ISSUE TITLE
mac端 c++版本 运行问题

### ISSUE THREAD

**Issue by vampire1204** [zhangxy0517/3D-Registration-with-Maximal-Cliques#27]
您好！
      首先对您在MAC上提出的想法非常感兴趣，觉得也非常的好，希望可以进一步借鉴相关思想，谢谢
      但是我个人在操作复现的时候出现了一些问题，想寻求您的指导，再次感谢

      问题描述：
      1）编译c++版本，环境：mac m1， 修改main.cpp中的路径，以及部分boost的随机取数。
      2）clion编译器、或者指令集编译   --demo
      3）报错的虽然和git有一个close的错很相似，但是感觉不是同样的

**Comment by vampire1204** [comment]
![image](https://github.com/zhangxy0517/3D-Registration-with-Maximal-Cliques/assets/142982473/2d992b64-2084-40bf-b8d0-65d1ead7d187)
这块的报错定位到问题点在：
igraph_weighted_adjacency(&g, &g_mat, IGRAPH_ADJ_UNDIRECTED, nullptr, igraph_loops_t::IGRAPH_LOOPS);会崩溃，由于对igraph这个库并不是很熟悉，所以似乎没办法进行下一步操作！
 十分期待您的解惑，抱歉，耽误您宝贵的时间，再一次感谢！！
/

**Comment by zhangxy0517** [comment]
您好，请确保igraph的版本为0.9.9。输入其他的数据是否也会出现这样的问题？

**Comment by vampire1204** [comment]
ok，可以过了，关了openmp以后速度好慢。 graph construction: 459.26  😭
遇到的问题：igraph 0.9.9编译的时候建议关键-Werror
谢谢！

**Comment by vampire1204** [comment]
关了

**Comment by vampire1204** [comment]
ok，可以过了，关了openmp以后速度好慢。 graph construction: 459.26 😭
遇到的问题：igraph 0.9.9编译的时候建议关键-Werror
谢谢！
