### ISSUE TITLE
数据集链接似乎失效了

### ISSUE THREAD

**Issue by caijillx** [zhangxy0517/3D-Registration-with-Maximal-Cliques#37]
![image](https://github.com/zhangxy0517/3D-Registration-with-Maximal-Cliques/assets/43942421/e637694d-f1b1-40bd-87b4-c8d408c4167e)
作者您好，您给出的dataset链接似乎是无效的，我这边无法正常访问，不知是我的问题，还是链接已失效。

**Comment by zhangxy0517** [comment]
感谢您的反馈！链接已更新

**Comment by caijillx** [comment]
thanks！
