### ISSUE TITLE
Graph Construction部分十分耗时

### ISSUE THREAD

**Issue by SuperShrimp** [zhangxy0517/3D-Registration-with-Maximal-Cliques#48]
作者好！我在linux环境下运行demo的时候发现Graph Construction的部分耗时十分严重，但根据代码中用双loop的方式推算耗时时间是十分合理的。我看到作者的readme文件中Graph Construction的部分只用4s左右就完成了，想知道这部分该如何优化呢?

我的demo结果如下
Start registration.
 graph construction: 515.753
 coefficient computation: 3.88628
0.41525->min(0.41525 0.793482 1.66802)
 clique computation: 0.442331
 clique selection: 0.258489
 hypothesis generation & evaluation: 5.12024
9716 : 521558
14 156.331
3.31526 3.29734 3.60479 3.54041 4.66473 5.57952 4.89386 5.40509 4.51781 4.51414 4.81748 5.44499 5.49566 4.15561 
  0.978359   -0.12634   0.163867   0.836844
  0.136967   0.989035 -0.0552166   0.161963
 -0.155095   0.076466   0.984936   0.106522
         0          0          0          1

**Comment by zhangxy0517** [comment]
请您确保严格按照说明配置环境以及编译运行。注意需要在release模式下编译

**Comment by SuperShrimp** [comment]
谢谢！问题解决了
