### ISSUE TITLE
请问python版本的和linux版本的性能一致吗？

### ISSUE THREAD

**Issue by songhc8** [zhangxy0517/3D-Registration-with-Maximal-Cliques#50]
您好，感谢分享。

我想请问下，python的demo和linux的性能一致吗，能否认为python是linux的cpp版本的平替呢，在不考虑效率的情况下。谢谢

**Comment by zhangxy0517** [comment]
python版缺少图规模处理部分，性能是有区别的，请参考问题#46。建议对照C++版本补充对应内容
