### ISSUE TITLE
question abtou hyper parameter cmp_thresh

### ISSUE THREAD

**Issue by songhc8** [zhangxy0517/3D-Registration-with-Maximal-Cliques#51]
thanks for sharing. 

how to set the value of cmp_thresh. its value is 0.99 in demo. what is the effect of the value. it should be larger or smaller?

https://github.com/zhangxy0517/3D-Registration-with-Maximal-Cliques/blob/f03f1a24ed74128433e40970fed6e01d6a09d780/Linux/main.cpp#L160C4-L160C95

**Comment by zhangxy0517** [comment]
cmp_thresh decides whether an edge should be formed between two nodes. A higher value will let fewer edges appear in the graph. If the magnitude of input correspondence is small (e.g., 500) or the inlier ratio is low (e.g., 1%), the value should be smaller (0.9). If the size of correspondences is quite large or the inlier ratio is high, it should be larger (e.g., 0.999).
