### ISSUE TITLE
Memory Leak Bug 内存泄漏问题

### ISSUE THREAD

**Issue by xieKKKi** [zhangxy0517/3D-Registration-with-Maximal-Cliques#54]
代码中似乎存在内存泄漏的问题，具体的表现是内存占用随着数据集的扩充而增长，而参数设置不佳会很容易导致out of memory的情况出现。一个更简单的复现方法是，使用registration函数对同一组correspondence配准一万次，可以观察到内存占用的线性增长过程。
https://github.com/zhangxy0517/3D-Registration-with-Maximal-Cliques/blob/d864bbab65eed5c49dbb858c6c2d52390db75056/Linux/registration.cpp#L1036

经过排查，定位到出现内存泄漏的函数是
https://github.com/zhangxy0517/3D-Registration-with-Maximal-Cliques/blob/d864bbab65eed5c49dbb858c6c2d52390db75056/Linux/registration.cpp#L1240
igraph_maximal_cliques是igraph的库函数，出现内存泄漏可能是igraph 0.9.9版本的bug，我把igraph升级到最新版本(0.10.13)，并略微修改了一点程序内容来适配新版本，问题得到了解决。

**Comment by zhangxy0517** [comment]
感谢您的帮助！我们会在近期适配新版igraph

**Comment by xieKKKi** [comment]
> 感谢您的帮助！我们会在近期适配新版igraph
Thanks for your great work!
