### ISSUE TITLE
inlier比例高时，二三百个匹配会产生几十万个clique_num，导致非常慢

### ISSUE THREAD

**Issue by songhc8** [zhangxy0517/3D-Registration-with-Maximal-Cliques#61]
谢谢分享，
最近一直在用您的方案。然后我有一个问题，比如我在2d图像上用sift匹配到284个点对。然后用对应的3维点进行mac的rt计算。
这时候位发现当cmp_threshold0.99时，clique_number有300000以上个。请问哪些参数可以控制clique_number的规模。可以认为sift匹配的结果基本是正确的结果。也就是给进mac的inlier的比例非常高。可能是98%都是正确的匹配。这种情况下主要的参数该怎么设置请问。

**Comment by zhangxy0517** [comment]
您可以尝试继续增大cmp_threshold（例如设为0.995,0.999），看是否能显著降低clique的数量。如果效果不明显，可以尝试修改判断是否执行减少图规模的阈值cluster_threshold，默认值是3，您需要根据实际情况设一个更小的值

**Comment by songhc8** [comment]
普适的参数不好调。实际落地的话可能建图这个过程要改进下。我明白现在是想通过resolution和cmp_threshold把dist 压缩到0-1的范围。只是现在有点参数敏感。其实可以不用考虑所有的dist，只考虑dist最近的一部分pair就可以了。这样graph的规模也小了，有效团簇的个数也小了我觉得。我修改了建图部分的算法，在我的案例是抛弃resolu和cmp_threshold这两个参数的。结果和原始代码比速度和稳定性都很好。
